model_name: openai/whisper-tiny
train_dataset: data/dpo_triplets/zeroth_train.jsonl
eval_dataset: data/dpo_triplets/zeroth_test.jsonl
output_dir: outputs/dpo/1021/whisper_tiny_zeroth
language: ko
task: transcribe
beta: 0.1
calibration_weight: 0.05
length_normalization: average
learning_rate: 5e-6
gradient_accumulation_steps: 8
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
num_train_epochs: 1
logging_steps: 100
eval_steps: 500
save_steps: 500
save_total_limit: 2
gradient_checkpointing: false
fp16: true
seed: 42
hf_home: .cache/huggingface
report_to:
  - tensorboard
